# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/bs299/Desktop/ECE350/processor/processor.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bs299/Desktop/ECE350/processor/processor.cache/wt [current_project]
set_property parent.project_path C:/Users/bs299/Desktop/ECE350/processor/processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/bs299/Desktop/ECE350/processor/processor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/bs299/Desktop/ECE350/processor/processor/RAM.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/ROM.v
  C:/Users/bs299/Desktop/ECE350/lab_6/VGATimingGenerator.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/alu.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/and_32.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/cla_adder_32.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/cla_adder_8.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/counter_64.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/d_control.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/dffe_ref.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/f_control.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/instruction_decoder.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/m_control.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/multdiv.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/mux_2.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/mux_2_65.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/mux_2_single.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/mux_4.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/mux_4_65.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/mux_8.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/mux_8_65.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/negate_32.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/or_32.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/processor.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/regfile.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/register.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/register_64.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/sign_extender.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/sll.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/sra.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/tff.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/tristate_32.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/w_control.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/x_control.v
  C:/Users/bs299/Desktop/ECE350/processor/processor/Wrapper.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/bs299/Desktop/ECE350/processor/master.xdc
set_property used_in_implementation false [get_files C:/Users/bs299/Desktop/ECE350/processor/master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
